development:  
  adapter: postgresql
  encoding: unicode
  database: mmagap
  pool: 5
  port: 5432
  host: localhost
  username: postgres
  password: postgres
  

test:
  adapter: postgresql
  encoding: unicode
  database: d3vlao7dl4vq69
  pool: 5
  port: 5432
  host: ec2-54-225-103-9.compute-1.amazonaws.com
  username: rrwbzejljxjmfc
  password: HfJqNL-pDrXqIas5sO5NbQxnTZ

production:
  adapter: postgresql
  encoding: unicode
  database: d3vlao7dl4vq69
  pool: 5
  port: 5432
  host: ec2-54-225-103-9.compute-1.amazonaws.com
  username: rrwbzejljxjmfc
  password: HfJqNL-pDrXqIas5sO5NbQxnTZ


